(cl:defpackage icar_msgs-srv
  (:use )
  (:export
   "TARGETRECOGNITION"
   "<TARGETRECOGNITION-REQUEST>"
   "TARGETRECOGNITION-REQUEST"
   "<TARGETRECOGNITION-RESPONSE>"
   "TARGETRECOGNITION-RESPONSE"
  ))

