(cl:defpackage icar_msgs-msg
  (:use )
  (:export
   "<ARMTARGET>"
   "ARMTARGET"
   "<PRECISEMOVEACTION>"
   "PRECISEMOVEACTION"
   "<PRECISEMOVEACTIONFEEDBACK>"
   "PRECISEMOVEACTIONFEEDBACK"
   "<PRECISEMOVEACTIONGOAL>"
   "PRECISEMOVEACTIONGOAL"
   "<PRECISEMOVEACTIONRESULT>"
   "PRECISEMOVEACTIONRESULT"
   "<PRECISEMOVEFEEDBACK>"
   "PRECISEMOVEFEEDBACK"
   "<PRECISEMOVEGOAL>"
   "PRECISEMOVEGOAL"
   "<PRECISEMOVERESULT>"
   "PRECISEMOVERESULT"
   "<VOICETARGET>"
   "VOICETARGET"
  ))

