// Auto-generated. Do not edit!

// (in-package icar_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PreciseMoveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.type = null;
      this.start_x = null;
      this.start_y = null;
      this.start_theta = null;
      this.goal_x = null;
      this.goal_y = null;
      this.goal_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('type')) {
        this.type = initObj.type
      }
      else {
        this.type = 0;
      }
      if (initObj.hasOwnProperty('start_x')) {
        this.start_x = initObj.start_x
      }
      else {
        this.start_x = 0.0;
      }
      if (initObj.hasOwnProperty('start_y')) {
        this.start_y = initObj.start_y
      }
      else {
        this.start_y = 0.0;
      }
      if (initObj.hasOwnProperty('start_theta')) {
        this.start_theta = initObj.start_theta
      }
      else {
        this.start_theta = 0.0;
      }
      if (initObj.hasOwnProperty('goal_x')) {
        this.goal_x = initObj.goal_x
      }
      else {
        this.goal_x = 0.0;
      }
      if (initObj.hasOwnProperty('goal_y')) {
        this.goal_y = initObj.goal_y
      }
      else {
        this.goal_y = 0.0;
      }
      if (initObj.hasOwnProperty('goal_theta')) {
        this.goal_theta = initObj.goal_theta
      }
      else {
        this.goal_theta = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PreciseMoveGoal
    // Serialize message field [type]
    bufferOffset = _serializer.char(obj.type, buffer, bufferOffset);
    // Serialize message field [start_x]
    bufferOffset = _serializer.float64(obj.start_x, buffer, bufferOffset);
    // Serialize message field [start_y]
    bufferOffset = _serializer.float64(obj.start_y, buffer, bufferOffset);
    // Serialize message field [start_theta]
    bufferOffset = _serializer.float64(obj.start_theta, buffer, bufferOffset);
    // Serialize message field [goal_x]
    bufferOffset = _serializer.float64(obj.goal_x, buffer, bufferOffset);
    // Serialize message field [goal_y]
    bufferOffset = _serializer.float64(obj.goal_y, buffer, bufferOffset);
    // Serialize message field [goal_theta]
    bufferOffset = _serializer.float64(obj.goal_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PreciseMoveGoal
    let len;
    let data = new PreciseMoveGoal(null);
    // Deserialize message field [type]
    data.type = _deserializer.char(buffer, bufferOffset);
    // Deserialize message field [start_x]
    data.start_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [start_y]
    data.start_y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [start_theta]
    data.start_theta = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [goal_x]
    data.goal_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [goal_y]
    data.goal_y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [goal_theta]
    data.goal_theta = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 49;
  }

  static datatype() {
    // Returns string type for a message object
    return 'icar_msgs/PreciseMoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a1ab3d2c84585a7413ba2a70ea4cd8ad';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    # if type is 0,then spin. if type is 1, then move. 
    char type
    float64 start_x
    float64 start_y
    float64 start_theta
    float64 goal_x
    float64 goal_y
    float64 goal_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PreciseMoveGoal(null);
    if (msg.type !== undefined) {
      resolved.type = msg.type;
    }
    else {
      resolved.type = 0
    }

    if (msg.start_x !== undefined) {
      resolved.start_x = msg.start_x;
    }
    else {
      resolved.start_x = 0.0
    }

    if (msg.start_y !== undefined) {
      resolved.start_y = msg.start_y;
    }
    else {
      resolved.start_y = 0.0
    }

    if (msg.start_theta !== undefined) {
      resolved.start_theta = msg.start_theta;
    }
    else {
      resolved.start_theta = 0.0
    }

    if (msg.goal_x !== undefined) {
      resolved.goal_x = msg.goal_x;
    }
    else {
      resolved.goal_x = 0.0
    }

    if (msg.goal_y !== undefined) {
      resolved.goal_y = msg.goal_y;
    }
    else {
      resolved.goal_y = 0.0
    }

    if (msg.goal_theta !== undefined) {
      resolved.goal_theta = msg.goal_theta;
    }
    else {
      resolved.goal_theta = 0.0
    }

    return resolved;
    }
};

module.exports = PreciseMoveGoal;
