// Auto-generated. Do not edit!

// (in-package icar_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PreciseMoveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_x = null;
      this.current_y = null;
      this.current_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('current_x')) {
        this.current_x = initObj.current_x
      }
      else {
        this.current_x = 0.0;
      }
      if (initObj.hasOwnProperty('current_y')) {
        this.current_y = initObj.current_y
      }
      else {
        this.current_y = 0.0;
      }
      if (initObj.hasOwnProperty('current_theta')) {
        this.current_theta = initObj.current_theta
      }
      else {
        this.current_theta = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PreciseMoveFeedback
    // Serialize message field [current_x]
    bufferOffset = _serializer.float64(obj.current_x, buffer, bufferOffset);
    // Serialize message field [current_y]
    bufferOffset = _serializer.float64(obj.current_y, buffer, bufferOffset);
    // Serialize message field [current_theta]
    bufferOffset = _serializer.float64(obj.current_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PreciseMoveFeedback
    let len;
    let data = new PreciseMoveFeedback(null);
    // Deserialize message field [current_x]
    data.current_x = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [current_y]
    data.current_y = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [current_theta]
    data.current_theta = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'icar_msgs/PreciseMoveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '135d5d86c0e48dabb265bb68e2f58746';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #define the feedback
    float64 current_x
    float64 current_y
    float64 current_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PreciseMoveFeedback(null);
    if (msg.current_x !== undefined) {
      resolved.current_x = msg.current_x;
    }
    else {
      resolved.current_x = 0.0
    }

    if (msg.current_y !== undefined) {
      resolved.current_y = msg.current_y;
    }
    else {
      resolved.current_y = 0.0
    }

    if (msg.current_theta !== undefined) {
      resolved.current_theta = msg.current_theta;
    }
    else {
      resolved.current_theta = 0.0
    }

    return resolved;
    }
};

module.exports = PreciseMoveFeedback;
