// Generated by gencpp from file icar_msgs/ArmTarget.msg
// DO NOT EDIT!


#ifndef ICAR_MSGS_MESSAGE_ARMTARGET_H
#define ICAR_MSGS_MESSAGE_ARMTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icar_msgs
{
template <class ContainerAllocator>
struct ArmTarget_
{
  typedef ArmTarget_<ContainerAllocator> Type;

  ArmTarget_()
    : type(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  ArmTarget_(const ContainerAllocator& _alloc)
    : type(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::icar_msgs::ArmTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icar_msgs::ArmTarget_<ContainerAllocator> const> ConstPtr;

}; // struct ArmTarget_

typedef ::icar_msgs::ArmTarget_<std::allocator<void> > ArmTarget;

typedef boost::shared_ptr< ::icar_msgs::ArmTarget > ArmTargetPtr;
typedef boost::shared_ptr< ::icar_msgs::ArmTarget const> ArmTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icar_msgs::ArmTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icar_msgs::ArmTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::icar_msgs::ArmTarget_<ContainerAllocator1> & lhs, const ::icar_msgs::ArmTarget_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::icar_msgs::ArmTarget_<ContainerAllocator1> & lhs, const ::icar_msgs::ArmTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace icar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::ArmTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::ArmTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::ArmTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::ArmTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::ArmTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::ArmTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icar_msgs::ArmTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a04abbe70114f5242b8f16424858f29";
  }

  static const char* value(const ::icar_msgs::ArmTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a04abbe70114f52ULL;
  static const uint64_t static_value2 = 0x42b8f16424858f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::icar_msgs::ArmTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icar_msgs/ArmTarget";
  }

  static const char* value(const ::icar_msgs::ArmTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icar_msgs::ArmTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::icar_msgs::ArmTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icar_msgs::ArmTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icar_msgs::ArmTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icar_msgs::ArmTarget_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICAR_MSGS_MESSAGE_ARMTARGET_H
