// Generated by gencpp from file icar_msgs/PreciseMoveResult.msg
// DO NOT EDIT!


#ifndef ICAR_MSGS_MESSAGE_PRECISEMOVERESULT_H
#define ICAR_MSGS_MESSAGE_PRECISEMOVERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icar_msgs
{
template <class ContainerAllocator>
struct PreciseMoveResult_
{
  typedef PreciseMoveResult_<ContainerAllocator> Type;

  PreciseMoveResult_()
    : done(false)
    , current_target_x(0.0)
    , current_target_y(0.0)
    , current_target_theta(0.0)
    , error()  {
    }
  PreciseMoveResult_(const ContainerAllocator& _alloc)
    : done(false)
    , current_target_x(0.0)
    , current_target_y(0.0)
    , current_target_theta(0.0)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;

   typedef double _current_target_x_type;
  _current_target_x_type current_target_x;

   typedef double _current_target_y_type;
  _current_target_y_type current_target_y;

   typedef double _current_target_theta_type;
  _current_target_theta_type current_target_theta;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct PreciseMoveResult_

typedef ::icar_msgs::PreciseMoveResult_<std::allocator<void> > PreciseMoveResult;

typedef boost::shared_ptr< ::icar_msgs::PreciseMoveResult > PreciseMoveResultPtr;
typedef boost::shared_ptr< ::icar_msgs::PreciseMoveResult const> PreciseMoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icar_msgs::PreciseMoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::icar_msgs::PreciseMoveResult_<ContainerAllocator1> & lhs, const ::icar_msgs::PreciseMoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done &&
    lhs.current_target_x == rhs.current_target_x &&
    lhs.current_target_y == rhs.current_target_y &&
    lhs.current_target_theta == rhs.current_target_theta &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::icar_msgs::PreciseMoveResult_<ContainerAllocator1> & lhs, const ::icar_msgs::PreciseMoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace icar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f63462f1fc4c7457f5cce6d87a41804";
  }

  static const char* value(const ::icar_msgs::PreciseMoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f63462f1fc4c745ULL;
  static const uint64_t static_value2 = 0x7f5cce6d87a41804ULL;
};

template<class ContainerAllocator>
struct DataType< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icar_msgs/PreciseMoveResult";
  }

  static const char* value(const ::icar_msgs::PreciseMoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#define the result\n"
"bool done\n"
"float64 current_target_x\n"
"float64 current_target_y\n"
"float64 current_target_theta\n"
"string error\n"
;
  }

  static const char* value(const ::icar_msgs::PreciseMoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
      stream.next(m.current_target_x);
      stream.next(m.current_target_y);
      stream.next(m.current_target_theta);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PreciseMoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icar_msgs::PreciseMoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icar_msgs::PreciseMoveResult_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "current_target_x: ";
    Printer<double>::stream(s, indent + "  ", v.current_target_x);
    s << indent << "current_target_y: ";
    Printer<double>::stream(s, indent + "  ", v.current_target_y);
    s << indent << "current_target_theta: ";
    Printer<double>::stream(s, indent + "  ", v.current_target_theta);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICAR_MSGS_MESSAGE_PRECISEMOVERESULT_H
