// Generated by gencpp from file icar_msgs/TargetRecognitionResponse.msg
// DO NOT EDIT!


#ifndef ICAR_MSGS_MESSAGE_TARGETRECOGNITIONRESPONSE_H
#define ICAR_MSGS_MESSAGE_TARGETRECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icar_msgs
{
template <class ContainerAllocator>
struct TargetRecognitionResponse_
{
  typedef TargetRecognitionResponse_<ContainerAllocator> Type;

  TargetRecognitionResponse_()
    : done(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  TargetRecognitionResponse_(const ContainerAllocator& _alloc)
    : done(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TargetRecognitionResponse_

typedef ::icar_msgs::TargetRecognitionResponse_<std::allocator<void> > TargetRecognitionResponse;

typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionResponse > TargetRecognitionResponsePtr;
typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionResponse const> TargetRecognitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator1> & lhs, const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator1> & lhs, const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace icar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1952cebf4a02203a3a399677db9f9cec";
  }

  static const char* value(const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1952cebf4a02203aULL;
  static const uint64_t static_value2 = 0x3a399677db9f9cecULL;
};

template<class ContainerAllocator>
struct DataType< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icar_msgs/TargetRecognitionResponse";
  }

  static const char* value(const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
;
  }

  static const char* value(const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetRecognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icar_msgs::TargetRecognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICAR_MSGS_MESSAGE_TARGETRECOGNITIONRESPONSE_H
