// Generated by gencpp from file icar_msgs/TargetRecognition.msg
// DO NOT EDIT!


#ifndef ICAR_MSGS_MESSAGE_TARGETRECOGNITION_H
#define ICAR_MSGS_MESSAGE_TARGETRECOGNITION_H

#include <ros/service_traits.h>


#include <icar_msgs/TargetRecognitionRequest.h>
#include <icar_msgs/TargetRecognitionResponse.h>


namespace icar_msgs
{

struct TargetRecognition
{

typedef TargetRecognitionRequest Request;
typedef TargetRecognitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetRecognition
} // namespace icar_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icar_msgs::TargetRecognition > {
  static const char* value()
  {
    return "c20858a17ef1f1c2a35dbc6267ecc06d";
  }

  static const char* value(const ::icar_msgs::TargetRecognition&) { return value(); }
};

template<>
struct DataType< ::icar_msgs::TargetRecognition > {
  static const char* value()
  {
    return "icar_msgs/TargetRecognition";
  }

  static const char* value(const ::icar_msgs::TargetRecognition&) { return value(); }
};


// service_traits::MD5Sum< ::icar_msgs::TargetRecognitionRequest> should match
// service_traits::MD5Sum< ::icar_msgs::TargetRecognition >
template<>
struct MD5Sum< ::icar_msgs::TargetRecognitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icar_msgs::TargetRecognition >::value();
  }
  static const char* value(const ::icar_msgs::TargetRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icar_msgs::TargetRecognitionRequest> should match
// service_traits::DataType< ::icar_msgs::TargetRecognition >
template<>
struct DataType< ::icar_msgs::TargetRecognitionRequest>
{
  static const char* value()
  {
    return DataType< ::icar_msgs::TargetRecognition >::value();
  }
  static const char* value(const ::icar_msgs::TargetRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icar_msgs::TargetRecognitionResponse> should match
// service_traits::MD5Sum< ::icar_msgs::TargetRecognition >
template<>
struct MD5Sum< ::icar_msgs::TargetRecognitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icar_msgs::TargetRecognition >::value();
  }
  static const char* value(const ::icar_msgs::TargetRecognitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icar_msgs::TargetRecognitionResponse> should match
// service_traits::DataType< ::icar_msgs::TargetRecognition >
template<>
struct DataType< ::icar_msgs::TargetRecognitionResponse>
{
  static const char* value()
  {
    return DataType< ::icar_msgs::TargetRecognition >::value();
  }
  static const char* value(const ::icar_msgs::TargetRecognitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICAR_MSGS_MESSAGE_TARGETRECOGNITION_H
