// Generated by gencpp from file icar_msgs/TargetRecognitionRequest.msg
// DO NOT EDIT!


#ifndef ICAR_MSGS_MESSAGE_TARGETRECOGNITIONREQUEST_H
#define ICAR_MSGS_MESSAGE_TARGETRECOGNITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icar_msgs
{
template <class ContainerAllocator>
struct TargetRecognitionRequest_
{
  typedef TargetRecognitionRequest_<ContainerAllocator> Type;

  TargetRecognitionRequest_()
    : name()  {
    }
  TargetRecognitionRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TargetRecognitionRequest_

typedef ::icar_msgs::TargetRecognitionRequest_<std::allocator<void> > TargetRecognitionRequest;

typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionRequest > TargetRecognitionRequestPtr;
typedef boost::shared_ptr< ::icar_msgs::TargetRecognitionRequest const> TargetRecognitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator1> & lhs, const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator1> & lhs, const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace icar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icar_msgs/TargetRecognitionRequest";
  }

  static const char* value(const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetRecognitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icar_msgs::TargetRecognitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICAR_MSGS_MESSAGE_TARGETRECOGNITIONREQUEST_H
